name: Bump version

on:
  push:
    branches: [ main ]

jobs:
  bumpVersion:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    permissions:
      contents: write
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.14
      - uses: actions/checkout@v4
      - name: Get commit data
        uses: rlespinasse/git-commit-data-action@v1.5.0
      - name: Set git author # Required for commitizen's bump command
        run: |
          git config user.name "${GIT_COMMIT_AUTHOR_NAME}"
          git config user.email "${GIT_COMMIT_AUTHOR_EMAIL}"
      - name: Setup Nu
        uses: hustcer/setup-nu@v3.13
        with:
          version: "0.99.0"
      - name: Get Nushell version from Cargo config
        shell: nu {0}
        run: open Cargo.toml | get dependencies.nu-plugin | save nushell_version
      - name: Build and release
        run: earthly --ci --push +bumpVersion