name: Release

on:
  push:
    branches: [ main ]

jobs:
  github-release:
    name: Create GitHub release
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Create Github release
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: 'true'
          tag: "$(git tag | tail -n 1)"
          skipIfReleaseExists: 'true'

  deploy-cargo:
    name: "Deploy to Cargo"
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.14
      - uses: actions/checkout@v4
      - name: Write cargo token to file # This avoids exposing it in logs
        run: echo $CARGO_REGISTRY_TOKEN >> cargo_token
      - name: Build and release
        run: earthly --ci --push +release
